-- LISTED vs. ADD-ON: does this product appear on /products?
--
-- A product is either LISTED (merchandised in the catalogue grid) or an ADD-ON
-- (absent from the grid, but fully reachable by slug and addable to the cart
-- from another product's page). This column is the whole of that distinction.
--
-- WHY A BOOLEAN AND NOT AN ENUM, AND NOT A CATEGORY.
--
--  * The question is closed and binary. The states an enum would add — hidden,
--    unpublished, retired — are `product.status` (DRAFT | ACTIVE | ARCHIVED),
--    which already governs whether the product is sellable AT ALL. A second
--    enum overlapping the first produces combinations with no defined winner
--    (ACTIVE + HIDDEN), and someone eventually has to guess.
--  * A category would have been the other obvious modelling. There is no
--    category admin UI in the dashboard (its routes are customers, discounts,
--    emails, inventory, jobs, orders, products), so "make add-ons a category"
--    silently means "build a category admin first", and the flag it is standing
--    in for would still be a flag — just one an operator sets by joining a
--    taxonomy.
--
-- ADDITIVE AND SAFE TO APPLY BEFORE THE CODE THAT READS IT. Migrations do not
-- run in the app container (see apps/api/Dockerfile) and Dokploy autoDeploys
-- this branch, so this column exists for some period while every running
-- instance neither reads nor writes it. DEFAULT true is what makes that window
-- uneventful: a row written by the currently-deployed application, which does
-- not know the column exists, is LISTED — exactly the behaviour every product
-- has today. There is no backfill because there is nothing to back-fill.
--
-- NO TABLE REWRITE AND NO LONG LOCK. Postgres 11+ stores the default for an
-- added NOT NULL column as a catalog-level "missing value" and materialises it
-- lazily on update, so this is a metadata change even though the column is NOT
-- NULL with a default. It takes an ACCESS EXCLUSIVE lock for the duration of
-- that catalog write only — microseconds — rather than for a scan of `product`,
-- which the storefront reads on every catalogue and product page.
--
-- NOT NULL rather than nullable, because there is no third state. A NULL would
-- have to mean "listed" anyway (that is what absent means), so permitting it
-- would only create a value every read has to COALESCE and one read eventually
-- will not.
ALTER TABLE "product" ADD COLUMN "listed" BOOLEAN NOT NULL DEFAULT true;

COMMENT ON COLUMN "product"."listed" IS
  'False = ADD-ON: hidden from the /products listing but still reachable by slug and purchasable. Not a visibility or access control — use "status" to make a product unsellable.';

-- NO INDEX, DELIBERATELY.
--
-- The one query this column narrows is the public catalogue listing, which is
-- already filtered by `status = ACTIVE` and `deletedAt IS NULL` and served by
-- "product_status_deletedAt_idx". `listed` is a low-cardinality boolean that
-- removes a handful of rows from a set that index has already reduced, so a
-- separate index would be chosen rarely and maintained on every write.
--
-- It is also the operationally safer choice here: CREATE INDEX takes a SHARE
-- lock that blocks writes for the length of the build, and the CONCURRENTLY
-- form that avoids it cannot run inside a transaction — which is precisely what
-- Prisma wraps each migration in. Should the catalogue ever grow enough to want
-- one, it belongs in its own migration, built CONCURRENTLY, outside this
-- transaction.

-- NO GRANT IS ISSUED. The runtime role's privileges are table-level
-- (`GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES` in
-- 20260720000100_invariants_sequences_grants), and a new COLUMN on an
-- already-granted table inherits them. Only a new TABLE, SEQUENCE or FUNCTION
-- would need a grant here — the distinction that
-- 20260910000000_invoice_counter had to make and this one does not.
