import { createHmac, randomUUID } from "node:crypto";

/**
 * A GENUINE Whop webhook signature builder.
 *
 * Why this exists rather than a stub that returns a canned event: if tests
 * bypassed signature verification, the raw-body path would never run, and the
 * single most common webhook integration defect — the body arriving JSON-parsed
 * so every signature check fails — would pass every test and fail every real
 * delivery.
 *
 * THE ONE PROPERTY THIS FILE MUST HAVE is that the bytes it produces are bytes
 * the REAL verifier verifies. It is asserted against the SDK's own
 * `unwrapWebhook`, which is what production calls, so if this drifts the suite
 * fails rather than testing a protocol the application does not speak.
 *
 * THE SCHEME IS STANDARD WEBHOOKS, and note how much stronger it is than the
 * TagadaPay CRM scheme it replaced:
 *
 *     webhook-id:        msg_<unique per delivery>
 *     webhook-timestamp: <unix seconds>
 *     webhook-signature: v1,<base64 hmac-sha256(key, "id.timestamp.body")>
 *
 * The TIMESTAMP IS INSIDE THE SIGNED MATERIAL. TagadaPay's HMAC covered the raw
 * body alone, so a captured delivery was replayable indefinitely at the
 * transport layer and `provider_event` was the only unconditional defence. Here
 * an attacker cannot advance the timestamp without invalidating the signature,
 * so `buildStaleWhopEvent` below can prove the window is actually enforced —
 * a test the previous scheme made impossible to write.
 *
 * THE `ws_` PREFIX IS PART OF THE KEY. Whop HMACs with the literal bytes of the
 * secret it issued, prefix included, and the `standardwebhooks` library the SDK
 * wraps base64-DECODES whatever key it is given — which is why the SDK
 * base64-encodes the secret first, and why this signer must do exactly the same
 * to produce bytes it will accept. Signing with the raw secret instead produces
 * a signature that verifies against nothing.
 */

export interface SignedWhopWebhook {
  /** Exact bytes to POST. Must reach the controller UNPARSED. */
  readonly payload: string;
  /** The same bytes as a Buffer, which is what the raw-body middleware attaches. */
  readonly rawBody: Buffer;
  /** The three signature headers, lower-cased exactly as Whop sends them. */
  readonly headers: Record<string, string>;
  /** The `webhook-id`, which is also the dedupe key the controller uses. */
  readonly deliveryId: string;
}

/** The webhook secret used across the suites. Never a real value. */
export const TEST_WHOP_WEBHOOK_SECRET = "ws_test_secret_for_unit_tests_only_0123456789";

export interface SignWhopEventOptions {
  readonly secret?: string;
  /** Delivery id. Repeat one to simulate a redelivery of the same event. */
  readonly deliveryId?: string;
  /** Seconds since the epoch. Defaults to now. */
  readonly timestampSeconds?: number;
}

/**
 * Sign an arbitrary event body with Whop's Standard Webhooks scheme.
 *
 * The `JSON.stringify` output IS the signed byte sequence. Re-serialising it
 * anywhere downstream changes key order or whitespace and breaks the signature —
 * which is exactly the failure this fake is designed to catch, so the payload is
 * returned alongside the headers rather than being regenerated by the caller.
 */
export function buildSignedWhopEvent(
  event: Readonly<Record<string, unknown>>,
  options: SignWhopEventOptions = {},
): SignedWhopWebhook {
  const secret = options.secret ?? TEST_WHOP_WEBHOOK_SECRET;
  const deliveryId = options.deliveryId ?? `msg_${randomUUID()}`;
  const timestamp = String(options.timestampSeconds ?? Math.floor(Date.now() / 1000));

  const payload = JSON.stringify(event);
  const rawBody = Buffer.from(payload, "utf8");

  // Base64 the whole secret, prefix included — see the note above. This mirrors
  // the SDK helper exactly; getting it wrong does not fail as a signature
  // mismatch but as a base64 decoder throw, which is far more confusing.
  const key = Buffer.from(Buffer.from(secret, "utf8").toString("base64"), "base64");
  const signature = createHmac("sha256", key)
    .update(`${deliveryId}.${timestamp}.${payload}`)
    .digest("base64");

  return {
    payload,
    rawBody,
    deliveryId,
    headers: {
      "webhook-id": deliveryId,
      "webhook-timestamp": timestamp,
      "webhook-signature": `v1,${signature}`,
    },
  };
}

/**
 * A signature that is well-formed but computed with the WRONG secret.
 *
 * Every webhook controller needs a test proving this is rejected. An endpoint
 * that accepts mis-signed payloads lets anyone on the internet mark any order
 * PAID — and the signature is the ENTIRE security boundary here, because Whop
 * presents no session and no credential of any other kind.
 */
export function buildForgedWhopEvent(
  event: Readonly<Record<string, unknown>>,
): SignedWhopWebhook {
  return buildSignedWhopEvent(event, { secret: "ws_attacker_controlled_value_0123456789" });
}

/**
 * A CORRECTLY signed delivery whose timestamp is outside the tolerance window.
 *
 * The replay test the TagadaPay scheme could not support: there, the timestamp
 * lived outside the signed material (or nowhere at all), so "stale" was not a
 * property the transport could express. Here the timestamp is covered by the
 * HMAC, so this produces a delivery that is authentic and must still be refused.
 */
export function buildStaleWhopEvent(
  event: Readonly<Record<string, unknown>>,
  ageSeconds = 3600,
): SignedWhopWebhook {
  return buildSignedWhopEvent(event, {
    timestampSeconds: Math.floor(Date.now() / 1000) - ageSeconds,
  });
}
